
const sessions = [
  {
    id: 1,
    name: "Morning Focus",
    category: "Focus",
    duration: "10 minutes",
    isLocked: false,
    isPremium: false,
    description: "Start your day with clarity and purpose.",
    image: "https://images.onlymyhealth.com/imported/images/2022/July/09_Jul_2022/main-morningmeditation.jpg",
  },
  {
    id: 2,
    name: "Deep Sleep",
    category: "Sleep",
    duration: "20 minutes",
    isLocked: true,
    isPremium: true,
    description: "Drift into a peaceful slumber with soothing sounds.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBIIJ4_tlsxBKQm4gtrDzpyzesORZxHzAlDw&s",
  },
  {
    id: 3,
    name: "Anxiety Relief",
    category: "Anxiety",
    duration: "15 minutes",
    isLocked: false,
    isPremium: false,
    description: "Calm your mind and find your inner peace.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR3Rf89BWphLYo3tabbkwJh4QN8U_LbVWquw&s",
  },
  {
    id: 4,
    name: "Premium Focus Session",
    category: "Focus",
    duration: "30 minutes",
    isLocked: true,
    isPremium: true,
    description: "Enhance your concentration with this exclusive session.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT56lUPVhTL5HlLd1KnVVAVnZ7dAt2TCNMiQ&s",
  },
  {
    id: 5,
    name: "Evening Relaxation",
    category: "Sleep",
    duration: "25 minutes",
    isLocked: false,
    isPremium: true,
    description: "Unwind and let go of the day's stress.",
    image: "https://media.istockphoto.com/id/1428299005/photo/man-is-sitting-in-a-camping-chair-on-the-background-of-a-forest-lake-on-a-beautiful-summer.jpg?s=612x612&w=0&k=20&c=dQZLIQGXpyLxWvtdpsRkpRXEqM4vZCGefzPtV9h_9Uk=",
  },
  {
    id: 6,
    name: "Midday Recharge",
    category: "Energy",
    duration: "12 minutes",
    isLocked: false,
    isPremium: false,
    description: "Recharge your body and mind during the day.",
    image: "https://media.licdn.com/dms/image/v2/D5612AQFocGoOnHPRxg/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1736194817020?e=2147483647&v=beta&t=60fbSg-aXILqvyj7Hviw-ZpRD0mW9vtbRRi6cSef_jY",
  },
  {
    id: 7,
    name: "Stress Release",
    category: "Anxiety",
    duration: "18 minutes",
    isLocked: true,
    isPremium: false,
    description: "Release built-up stress and tension naturally.",
    image: "https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs3/330958289/original/79a0ecf2a33047f572bf608ed6ebad0c12f14cd7/good-at-talking-to-stranger-and-reduce-their-stress.png",
  },
  {
    id: 8,
    name: "Night Calm",
    category: "Sleep",
    duration: "22 minutes",
    isLocked: false,
    isPremium: true,
    description: "Fall asleep with a calming nighttime meditation.",
    image: "https://thumbs.dreamstime.com/b/full-moon-shines-brightly-behind-palm-tree-calm-night-369203626.jpg",
  },
];

export default sessions;
