const transactions = [
    {
      id: 1,
      title: "Grocery Store",
      amount: 1200,
      transactionType: "debit",
      date: "2025-04-01",
      category: "Groceries",
      status: "Completed",
    },
    {
      id: 2,
      title: "Salary Credit",
      amount: 45000,
      transactionType: "credit",
      date: "2025-04-01",
      category: "Income",
      status: "Completed",
    },
    {
      id: 3,
      title: "EMI Payment",
      amount: 7000,
      transactionType: "debit",
      date: "2025-04-03",
      category: "EMI",
      status: "Completed",
    },
    {
      id: 4,
      title: "Dining at Restaurant",
      amount: 950,
      transactionType: "debit",
      date: "2025-04-05",
      category: "Food",
      status: "Completed",
    },
    {
      id: 5,
      title: "Freelance Project",
      amount: 5000,
      transactionType: "credit",
      date: "2025-04-07",
      category: "Income",
      status: "Completed",
    },
    {
      id: 6,
      title: "Online Shopping",
      amount: 1600,
      transactionType: "debit",
      date: "2025-04-09",
      category: "Shopping",
      status: "Pending",
    },
    {
      id: 7,
      title: "Electricity Bill",
      amount: 1250,
      transactionType: "debit",
      date: "2025-04-10",
      category: "Utilities",
      status: "Completed",
    },
    {
      id: 8,
      title: "Cashback Reward",
      amount: 150,
      transactionType: "credit",
      date: "2025-04-11",
      category: "Reward",
      status: "Completed",
    },
    {
      id: 9,
      title: "Loan Repayment",
      amount: 8000,
      transactionType: "debit",
      date: "2025-04-12",
      category: "Loans",
      status: "Failed",
    },
    {
      id: 10,
      title: "Gift Received",
      amount: 1000,
      transactionType: "credit",
      date: "2025-04-13",
      category: "Gift",
      status: "Completed",
    },
    {
      id: 11,
      title: "Subscription Renewal",
      amount: 499,
      transactionType: "debit",
      date: "2025-04-14",
      category: "Subscription",
      status: "Completed",
    },
    {
      id: 12,
      title: "Book Purchase",
      amount: 750,
      transactionType: "debit",
      date: "2025-04-14",
      category: "Books",
      status: "Completed",
    }
  ];
  
  export default transactions;
  