const movies = [
  {
    id: 1,
    title: "HIT 3",
    showtimes: ["10:30 AM", "1:00 PM", "3:30 PM"],
    theater: "Cineplex 1",
    rating: 4.5,
    language: "Telugu",
    genre: "Action-Thriller",
    isFull: false,
    isFree: false,
    isPremiere: true,
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BOGJlMTM2OWUtYTQwNy00YmM3LTlkOTctMDBjY2ExN2JjY2UzXkEyXkFqcGc@._V1_.jpg'
  },
  {
    id: 2,
    title: "Salaar",
    showtimes: ["11:00 AM", "2:00 PM", "5:00 PM"],
    theater: "Cineplex 2",
    rating: 3.8,
    language: "Telugu",
    genre: "Action",
    isFull: true,
    isFree: false,
    isPremiere: false,
    imageUrl: 'https://static.toiimg.com/photo/101561141.jpeg'
  },
  {
    id: 3,
    title: "Varasudu",
    showtimes: ["12:00 PM", "3:00 PM", "6:00 PM"],
    theater: "Cineplex 3",
    rating: 4.2,
    language: "Telugu",
    genre: "Drama",
    isFull: false,
    isFree: false,
    isPremiere: true,
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpGWEDaotDqP0z0G_8-IXpeU0tM0NiYiFNNw&s'
  },
  {
    id: 4,
    title: "Jawan",
    showtimes: ["1:00 PM", "4:00 PM", "7:00 PM"],
    theater: "Cineplex 4",
    rating: 4.7,
    language: "Telugu",
    genre: "Action",
    isFull: false,
    isFree: false,
    isPremiere: true,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/3/39/Jawan_film_poster.jpg'
  },
  {
    id: 5,
    title: "Kushi",
    showtimes: ["2:00 PM", "5:00 PM", "8:00 PM"],
    theater: "Cineplex 5",
    rating: 4.0,
    language: "Telugu",
    genre: "Romance",
    isFull: false,
    isFree: false,
    isPremiere: false,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/65/Kushi_%282022_film%29.jpg'
  },
  {
    id: 6,
    title: "Adipurush",
    showtimes: ["3:00 PM", "6:00 PM", "9:00 PM"],
    theater: "Cineplex 6",
    rating: 4.5,
    language: "Telugu",
    genre: "Mythology",
    isFull: false,
    isFree: false,
    isPremiere: true,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cf/Adipurush_poster.jpeg'
  },
  {
    id: 7,
    title: "Dhamaka",
    showtimes: ["4:00 PM", "7:00 PM"],
    theater: "Cineplex 7",
    rating: 4.3,
    language: "Telugu",
    genre: "Action-Comedy",
    isFull: false,
    isFree: false,
    isPremiere: false,
    imageUrl: 'https://assetscdn1.paytm.com/images/cinema/dhamaka-min-5278f6a0-5441-11ed-83cc-e989aa660c2a.jpg'
  },
  {
    id: 8,
    title: "Sita Ramam",
    showtimes: ["5:00 PM", "8:00 PM"],
    theater: "Cineplex 8",
    rating: 4.6,
    language: "Telugu",
    genre: "Drama",
    isFull: false,
    isFree: false,
    isPremiere: false,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Sita_Ramam.jpg'
  },
  {
    id: 9,
    title: "Dasara",
    showtimes: ["6:00 PM", "9:00 PM"],
    theater: "Cineplex 9",
    rating: 4.4,
    language: "Telugu",
    genre: "Action-Drama",
    isFull: false,
    isFree: false,
    isPremiere: true,
    imageUrl: 'https://static.hindutamil.in/hindu/uploads/news/2023/03/25/xlarge/965638.jpg'
  },
  {
    id: 10,
    title: "Davaar",
    showtimes: ["2:00 PM", "5:00 PM", "8:00 PM"],
    theater: "Cineplex 12",
    rating: 4.3,
    language: "Telugu",
    genre: "Action-Drama",
    isFull: false,
    isFree: false,
    isPremiere: true,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Devara_Part_1.jpg'
  },
  {
    id: 11,
    title: "Liger",
    showtimes: ["1:00 PM", "4:00 PM", "7:00 PM"],
    theater: "Cineplex 11",
    rating: 4.0,
    language: "Telugu",
    genre: "Action-Romance",
    isFull: false,
    isFree: false,
    isPremiere: false,
    imageUrl: 'https://th-i.thgim.com/public/incoming/upreuz/article65809505.ece/alternates/FREE_1200/Liger%20still.jpg'
  },
  {
    id: 12,
    title: "Pushpa: The Rise",
    showtimes: ["1:30 PM", "4:30 PM", "7:30 PM"],
    theater: "Cineplex 13",
    rating: 4.5,
    language: "Telugu",
    genre: "Action-Drama",
    isFull: false,
    isFree: false,
    isPremiere: false,
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BZjllNTdiM2QtYjQ0Ni00ZGM1LWFlYmUtNWY0YjMzYWIxOTYxXkEyXkFqcGc@._V1_.jpg'
  }
];

export default movies;